# Generated by Django 5.0.7 on 2024-07-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_task_type_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField(verbose_name='Дата начала')),
                ('date_ended', models.DateField(null=True, verbose_name='Дата окончания')),
                ('name', models.CharField(max_length=50, verbose_name='Название проекта')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'Project',
            },
        ),
    ]
