# Generated by Django 5.0.7 on 2024-07-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_ended',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
